version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev  # Installs gobject-introspection-dev
      - store_artifacts:
          path: bar_chart_output.png  
          destination: bar_chart_output.png #uploads an artifact
      - store_artifacts:
          path: box_plot_output.png  
          destination: box_plot_output.png #uploads an artifact
      - store_artifacts:
          path: trend_disorder_output.png
          destination: trend_disorder_output.png #uploads an artifact
      - store_artifacts:
          path: scatter_disorder_plot.png
          destination: scatter_disorder_plot.png #uploads an artifact      
      - store_artifacts:
          path: regional_bar_chart.png
          destination: regional_bar_chart.png #uploads an artifact
      - store_artifacts:
          path: population_vs_disorder.png
          destination: population_vs_disorder.png #uploads an artifact        
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
